Dystopia:
    MOTD: <red>Dystopia</red>
    SubName: ""
Whitelist:
    Enabled: false
    Players:
        - player1
        - player2
Advanced:
    Port: 19132
    XBOX-Authentication: true
    Cache-Path: assets
    Default-World: ""
    Database-Path: dystopia.db
Resources:
    Path: assets/resources
    Required: true
    Content-Key: enter key here
